/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteRouteImport } from './routes/_base/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as BaseAuthenticationRouteRouteImport } from './routes/_base/_authentication/route'
import { Route as MainWithRightAsideRouteRouteImport } from './routes/_main/_with-right-aside/route'
import { Route as MainDiscussionsRouteRouteImport } from './routes/_main/discussions/route'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as BaseAuthenticationIndexRouteImport } from './routes/_base/_authentication/index'
import { Route as BaseAuthenticationCompleteSignupRouteImport } from './routes/_base/_authentication/complete-signup'
import { Route as BaseAuthenticationNewPasswordRouteImport } from './routes/_base/_authentication/new-password'
import { Route as BaseAuthenticationPasswordResetRouteImport } from './routes/_base/_authentication/password-reset'
import { Route as BaseAuthenticationSignupRouteImport } from './routes/_base/_authentication/signup'
import { Route as BaseAuthenticationUserVerificationRouteImport } from './routes/_base/_authentication/user-verification'
import { Route as MainWithRightAsideUsernameRouteImport } from './routes/_main/_with-right-aside/$username'
import { Route as MainWithRightAsideBookmarkCollectionsRouteImport } from './routes/_main/_with-right-aside/bookmark-collections'
import { Route as MainWithRightAsideBookmarksRouteImport } from './routes/_main/_with-right-aside/bookmarks'
import { Route as MainWithRightAsideHomeRouteImport } from './routes/_main/_with-right-aside/home'
import { Route as MainWithRightAsideNotificationsRouteImport } from './routes/_main/_with-right-aside/notifications'
import { Route as MainWithRightAsideSearchRouteImport } from './routes/_main/_with-right-aside/search'
import { Route as MainDiscussionsIndexRouteImport } from './routes/_main/discussions/index'
import { Route as MainDiscussionsDiscussionIdRouteImport } from './routes/_main/discussions/$discussionId'
import { Route as MainWithRightAsidePostsPostIdRouteImport } from './routes/_main/_with-right-aside/posts.$postId'

const BaseRouteRoute = BaseRouteRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseAuthenticationRouteRoute = BaseAuthenticationRouteRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => BaseRouteRoute,
} as any)
const MainWithRightAsideRouteRoute = MainWithRightAsideRouteRouteImport.update({
  id: '/_with-right-aside',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDiscussionsRouteRoute = MainDiscussionsRouteRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const BaseAuthenticationIndexRoute = BaseAuthenticationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseAuthenticationRouteRoute,
} as any)
const BaseAuthenticationCompleteSignupRoute =
  BaseAuthenticationCompleteSignupRouteImport.update({
    id: '/complete-signup',
    path: '/complete-signup',
    getParentRoute: () => BaseAuthenticationRouteRoute,
  } as any)
const BaseAuthenticationNewPasswordRoute =
  BaseAuthenticationNewPasswordRouteImport.update({
    id: '/new-password',
    path: '/new-password',
    getParentRoute: () => BaseAuthenticationRouteRoute,
  } as any)
const BaseAuthenticationPasswordResetRoute =
  BaseAuthenticationPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => BaseAuthenticationRouteRoute,
  } as any)
const BaseAuthenticationSignupRoute =
  BaseAuthenticationSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => BaseAuthenticationRouteRoute,
  } as any)
const BaseAuthenticationUserVerificationRoute =
  BaseAuthenticationUserVerificationRouteImport.update({
    id: '/user-verification',
    path: '/user-verification',
    getParentRoute: () => BaseAuthenticationRouteRoute,
  } as any)
const MainWithRightAsideUsernameRoute =
  MainWithRightAsideUsernameRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => MainWithRightAsideRouteRoute,
  } as any)
const MainWithRightAsideBookmarkCollectionsRoute =
  MainWithRightAsideBookmarkCollectionsRouteImport.update({
    id: '/bookmark-collections',
    path: '/bookmark-collections',
    getParentRoute: () => MainWithRightAsideRouteRoute,
  } as any)
const MainWithRightAsideBookmarksRoute =
  MainWithRightAsideBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => MainWithRightAsideRouteRoute,
  } as any)
const MainWithRightAsideHomeRoute = MainWithRightAsideHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainWithRightAsideRouteRoute,
} as any)
const MainWithRightAsideNotificationsRoute =
  MainWithRightAsideNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => MainWithRightAsideRouteRoute,
  } as any)
const MainWithRightAsideSearchRoute =
  MainWithRightAsideSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => MainWithRightAsideRouteRoute,
  } as any)
const MainDiscussionsIndexRoute = MainDiscussionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainDiscussionsRouteRoute,
} as any)
const MainDiscussionsDiscussionIdRoute =
  MainDiscussionsDiscussionIdRouteImport.update({
    id: '/$discussionId',
    path: '/$discussionId',
    getParentRoute: () => MainDiscussionsRouteRoute,
  } as any)
const MainWithRightAsidePostsPostIdRoute =
  MainWithRightAsidePostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => MainWithRightAsideRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseAuthenticationIndexRoute
  '/discussions': typeof MainDiscussionsRouteRouteWithChildren
  '/settings': typeof MainSettingsRoute
  '/complete-signup': typeof BaseAuthenticationCompleteSignupRoute
  '/new-password': typeof BaseAuthenticationNewPasswordRoute
  '/password-reset': typeof BaseAuthenticationPasswordResetRoute
  '/signup': typeof BaseAuthenticationSignupRoute
  '/user-verification': typeof BaseAuthenticationUserVerificationRoute
  '/$username': typeof MainWithRightAsideUsernameRoute
  '/bookmark-collections': typeof MainWithRightAsideBookmarkCollectionsRoute
  '/bookmarks': typeof MainWithRightAsideBookmarksRoute
  '/home': typeof MainWithRightAsideHomeRoute
  '/notifications': typeof MainWithRightAsideNotificationsRoute
  '/search': typeof MainWithRightAsideSearchRoute
  '/discussions/$discussionId': typeof MainDiscussionsDiscussionIdRoute
  '/discussions/': typeof MainDiscussionsIndexRoute
  '/posts/$postId': typeof MainWithRightAsidePostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof BaseAuthenticationIndexRoute
  '/settings': typeof MainSettingsRoute
  '/complete-signup': typeof BaseAuthenticationCompleteSignupRoute
  '/new-password': typeof BaseAuthenticationNewPasswordRoute
  '/password-reset': typeof BaseAuthenticationPasswordResetRoute
  '/signup': typeof BaseAuthenticationSignupRoute
  '/user-verification': typeof BaseAuthenticationUserVerificationRoute
  '/$username': typeof MainWithRightAsideUsernameRoute
  '/bookmark-collections': typeof MainWithRightAsideBookmarkCollectionsRoute
  '/bookmarks': typeof MainWithRightAsideBookmarksRoute
  '/home': typeof MainWithRightAsideHomeRoute
  '/notifications': typeof MainWithRightAsideNotificationsRoute
  '/search': typeof MainWithRightAsideSearchRoute
  '/discussions/$discussionId': typeof MainDiscussionsDiscussionIdRoute
  '/discussions': typeof MainDiscussionsIndexRoute
  '/posts/$postId': typeof MainWithRightAsidePostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_base': typeof BaseRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_base/_authentication': typeof BaseAuthenticationRouteRouteWithChildren
  '/_main/_with-right-aside': typeof MainWithRightAsideRouteRouteWithChildren
  '/_main/discussions': typeof MainDiscussionsRouteRouteWithChildren
  '/_main/settings': typeof MainSettingsRoute
  '/_base/_authentication/complete-signup': typeof BaseAuthenticationCompleteSignupRoute
  '/_base/_authentication/new-password': typeof BaseAuthenticationNewPasswordRoute
  '/_base/_authentication/password-reset': typeof BaseAuthenticationPasswordResetRoute
  '/_base/_authentication/signup': typeof BaseAuthenticationSignupRoute
  '/_base/_authentication/user-verification': typeof BaseAuthenticationUserVerificationRoute
  '/_main/_with-right-aside/$username': typeof MainWithRightAsideUsernameRoute
  '/_main/_with-right-aside/bookmark-collections': typeof MainWithRightAsideBookmarkCollectionsRoute
  '/_main/_with-right-aside/bookmarks': typeof MainWithRightAsideBookmarksRoute
  '/_main/_with-right-aside/home': typeof MainWithRightAsideHomeRoute
  '/_main/_with-right-aside/notifications': typeof MainWithRightAsideNotificationsRoute
  '/_main/_with-right-aside/search': typeof MainWithRightAsideSearchRoute
  '/_main/discussions/$discussionId': typeof MainDiscussionsDiscussionIdRoute
  '/_base/_authentication/': typeof BaseAuthenticationIndexRoute
  '/_main/discussions/': typeof MainDiscussionsIndexRoute
  '/_main/_with-right-aside/posts/$postId': typeof MainWithRightAsidePostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discussions'
    | '/settings'
    | '/complete-signup'
    | '/new-password'
    | '/password-reset'
    | '/signup'
    | '/user-verification'
    | '/$username'
    | '/bookmark-collections'
    | '/bookmarks'
    | '/home'
    | '/notifications'
    | '/search'
    | '/discussions/$discussionId'
    | '/discussions/'
    | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/complete-signup'
    | '/new-password'
    | '/password-reset'
    | '/signup'
    | '/user-verification'
    | '/$username'
    | '/bookmark-collections'
    | '/bookmarks'
    | '/home'
    | '/notifications'
    | '/search'
    | '/discussions/$discussionId'
    | '/discussions'
    | '/posts/$postId'
  id:
    | '__root__'
    | '/_base'
    | '/_main'
    | '/_base/_authentication'
    | '/_main/_with-right-aside'
    | '/_main/discussions'
    | '/_main/settings'
    | '/_base/_authentication/complete-signup'
    | '/_base/_authentication/new-password'
    | '/_base/_authentication/password-reset'
    | '/_base/_authentication/signup'
    | '/_base/_authentication/user-verification'
    | '/_main/_with-right-aside/$username'
    | '/_main/_with-right-aside/bookmark-collections'
    | '/_main/_with-right-aside/bookmarks'
    | '/_main/_with-right-aside/home'
    | '/_main/_with-right-aside/notifications'
    | '/_main/_with-right-aside/search'
    | '/_main/discussions/$discussionId'
    | '/_base/_authentication/'
    | '/_main/discussions/'
    | '/_main/_with-right-aside/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BaseRouteRoute: typeof BaseRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/_authentication': {
      id: '/_base/_authentication'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseAuthenticationRouteRouteImport
      parentRoute: typeof BaseRouteRoute
    }
    '/_main/_with-right-aside': {
      id: '/_main/_with-right-aside'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainWithRightAsideRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/discussions': {
      id: '/_main/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof MainDiscussionsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_base/_authentication/': {
      id: '/_base/_authentication/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseAuthenticationIndexRouteImport
      parentRoute: typeof BaseAuthenticationRouteRoute
    }
    '/_base/_authentication/complete-signup': {
      id: '/_base/_authentication/complete-signup'
      path: '/complete-signup'
      fullPath: '/complete-signup'
      preLoaderRoute: typeof BaseAuthenticationCompleteSignupRouteImport
      parentRoute: typeof BaseAuthenticationRouteRoute
    }
    '/_base/_authentication/new-password': {
      id: '/_base/_authentication/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof BaseAuthenticationNewPasswordRouteImport
      parentRoute: typeof BaseAuthenticationRouteRoute
    }
    '/_base/_authentication/password-reset': {
      id: '/_base/_authentication/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof BaseAuthenticationPasswordResetRouteImport
      parentRoute: typeof BaseAuthenticationRouteRoute
    }
    '/_base/_authentication/signup': {
      id: '/_base/_authentication/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof BaseAuthenticationSignupRouteImport
      parentRoute: typeof BaseAuthenticationRouteRoute
    }
    '/_base/_authentication/user-verification': {
      id: '/_base/_authentication/user-verification'
      path: '/user-verification'
      fullPath: '/user-verification'
      preLoaderRoute: typeof BaseAuthenticationUserVerificationRouteImport
      parentRoute: typeof BaseAuthenticationRouteRoute
    }
    '/_main/_with-right-aside/$username': {
      id: '/_main/_with-right-aside/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof MainWithRightAsideUsernameRouteImport
      parentRoute: typeof MainWithRightAsideRouteRoute
    }
    '/_main/_with-right-aside/bookmark-collections': {
      id: '/_main/_with-right-aside/bookmark-collections'
      path: '/bookmark-collections'
      fullPath: '/bookmark-collections'
      preLoaderRoute: typeof MainWithRightAsideBookmarkCollectionsRouteImport
      parentRoute: typeof MainWithRightAsideRouteRoute
    }
    '/_main/_with-right-aside/bookmarks': {
      id: '/_main/_with-right-aside/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof MainWithRightAsideBookmarksRouteImport
      parentRoute: typeof MainWithRightAsideRouteRoute
    }
    '/_main/_with-right-aside/home': {
      id: '/_main/_with-right-aside/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainWithRightAsideHomeRouteImport
      parentRoute: typeof MainWithRightAsideRouteRoute
    }
    '/_main/_with-right-aside/notifications': {
      id: '/_main/_with-right-aside/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MainWithRightAsideNotificationsRouteImport
      parentRoute: typeof MainWithRightAsideRouteRoute
    }
    '/_main/_with-right-aside/search': {
      id: '/_main/_with-right-aside/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainWithRightAsideSearchRouteImport
      parentRoute: typeof MainWithRightAsideRouteRoute
    }
    '/_main/discussions/': {
      id: '/_main/discussions/'
      path: '/'
      fullPath: '/discussions/'
      preLoaderRoute: typeof MainDiscussionsIndexRouteImport
      parentRoute: typeof MainDiscussionsRouteRoute
    }
    '/_main/discussions/$discussionId': {
      id: '/_main/discussions/$discussionId'
      path: '/$discussionId'
      fullPath: '/discussions/$discussionId'
      preLoaderRoute: typeof MainDiscussionsDiscussionIdRouteImport
      parentRoute: typeof MainDiscussionsRouteRoute
    }
    '/_main/_with-right-aside/posts/$postId': {
      id: '/_main/_with-right-aside/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof MainWithRightAsidePostsPostIdRouteImport
      parentRoute: typeof MainWithRightAsideRouteRoute
    }
  }
}

interface BaseAuthenticationRouteRouteChildren {
  BaseAuthenticationCompleteSignupRoute: typeof BaseAuthenticationCompleteSignupRoute
  BaseAuthenticationNewPasswordRoute: typeof BaseAuthenticationNewPasswordRoute
  BaseAuthenticationPasswordResetRoute: typeof BaseAuthenticationPasswordResetRoute
  BaseAuthenticationSignupRoute: typeof BaseAuthenticationSignupRoute
  BaseAuthenticationUserVerificationRoute: typeof BaseAuthenticationUserVerificationRoute
  BaseAuthenticationIndexRoute: typeof BaseAuthenticationIndexRoute
}

const BaseAuthenticationRouteRouteChildren: BaseAuthenticationRouteRouteChildren =
  {
    BaseAuthenticationCompleteSignupRoute:
      BaseAuthenticationCompleteSignupRoute,
    BaseAuthenticationNewPasswordRoute: BaseAuthenticationNewPasswordRoute,
    BaseAuthenticationPasswordResetRoute: BaseAuthenticationPasswordResetRoute,
    BaseAuthenticationSignupRoute: BaseAuthenticationSignupRoute,
    BaseAuthenticationUserVerificationRoute:
      BaseAuthenticationUserVerificationRoute,
    BaseAuthenticationIndexRoute: BaseAuthenticationIndexRoute,
  }

const BaseAuthenticationRouteRouteWithChildren =
  BaseAuthenticationRouteRoute._addFileChildren(
    BaseAuthenticationRouteRouteChildren,
  )

interface BaseRouteRouteChildren {
  BaseAuthenticationRouteRoute: typeof BaseAuthenticationRouteRouteWithChildren
}

const BaseRouteRouteChildren: BaseRouteRouteChildren = {
  BaseAuthenticationRouteRoute: BaseAuthenticationRouteRouteWithChildren,
}

const BaseRouteRouteWithChildren = BaseRouteRoute._addFileChildren(
  BaseRouteRouteChildren,
)

interface MainWithRightAsideRouteRouteChildren {
  MainWithRightAsideUsernameRoute: typeof MainWithRightAsideUsernameRoute
  MainWithRightAsideBookmarkCollectionsRoute: typeof MainWithRightAsideBookmarkCollectionsRoute
  MainWithRightAsideBookmarksRoute: typeof MainWithRightAsideBookmarksRoute
  MainWithRightAsideHomeRoute: typeof MainWithRightAsideHomeRoute
  MainWithRightAsideNotificationsRoute: typeof MainWithRightAsideNotificationsRoute
  MainWithRightAsideSearchRoute: typeof MainWithRightAsideSearchRoute
  MainWithRightAsidePostsPostIdRoute: typeof MainWithRightAsidePostsPostIdRoute
}

const MainWithRightAsideRouteRouteChildren: MainWithRightAsideRouteRouteChildren =
  {
    MainWithRightAsideUsernameRoute: MainWithRightAsideUsernameRoute,
    MainWithRightAsideBookmarkCollectionsRoute:
      MainWithRightAsideBookmarkCollectionsRoute,
    MainWithRightAsideBookmarksRoute: MainWithRightAsideBookmarksRoute,
    MainWithRightAsideHomeRoute: MainWithRightAsideHomeRoute,
    MainWithRightAsideNotificationsRoute: MainWithRightAsideNotificationsRoute,
    MainWithRightAsideSearchRoute: MainWithRightAsideSearchRoute,
    MainWithRightAsidePostsPostIdRoute: MainWithRightAsidePostsPostIdRoute,
  }

const MainWithRightAsideRouteRouteWithChildren =
  MainWithRightAsideRouteRoute._addFileChildren(
    MainWithRightAsideRouteRouteChildren,
  )

interface MainDiscussionsRouteRouteChildren {
  MainDiscussionsDiscussionIdRoute: typeof MainDiscussionsDiscussionIdRoute
  MainDiscussionsIndexRoute: typeof MainDiscussionsIndexRoute
}

const MainDiscussionsRouteRouteChildren: MainDiscussionsRouteRouteChildren = {
  MainDiscussionsDiscussionIdRoute: MainDiscussionsDiscussionIdRoute,
  MainDiscussionsIndexRoute: MainDiscussionsIndexRoute,
}

const MainDiscussionsRouteRouteWithChildren =
  MainDiscussionsRouteRoute._addFileChildren(MainDiscussionsRouteRouteChildren)

interface MainRouteRouteChildren {
  MainWithRightAsideRouteRoute: typeof MainWithRightAsideRouteRouteWithChildren
  MainDiscussionsRouteRoute: typeof MainDiscussionsRouteRouteWithChildren
  MainSettingsRoute: typeof MainSettingsRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainWithRightAsideRouteRoute: MainWithRightAsideRouteRouteWithChildren,
  MainDiscussionsRouteRoute: MainDiscussionsRouteRouteWithChildren,
  MainSettingsRoute: MainSettingsRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  BaseRouteRoute: BaseRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
