services:
  # Kong Gateway
  kong:
    image: kong:3.7
    container_name: social-media-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong:/kong/declarative:ro
    depends_on:
      - authentication-service-postgres
      - user-service-postgres
      - content-service-postgres
    networks:
      - social-media-network

  # PostgreSQL for authentication-service
  authentication-service-postgres:
    image: postgres:16-alpine
    container_name: social-media-authentication-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_media_authentication
    ports:
      - "54321:5432"
    volumes:
      - authentication-service-postgres-data:/var/lib/postgresql/data
    networks:
      - social-media-network

  # PostgreSQL for user-service
  user-service-postgres:
    image: postgres:16-alpine
    container_name: social-media-user-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_media_user
    ports:
      - "54322:5432"
    volumes:
      - user-service-postgres-data:/var/lib/postgresql/data
    networks:
      - social-media-network

  # PostgreSQL for content-service
  content-service-postgres:
    image: postgres:16-alpine
    container_name: social-media-content-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_media_content
    ports:
      - "54324:5432"
    volumes:
      - content-service-postgres-data:/var/lib/postgresql/data
    networks:
      - social-media-network

volumes:
  authentication-service-postgres-data:
  user-service-postgres-data:
  content-service-postgres-data:

networks:
  social-media-network:
    driver: bridge
