const USER_VERIFICATION_GOALS = {
	signup: "SIGNUP",
	login: "LOGIN",
	passwordReset: "PASSWORD_RESET",
} as const;

const MAX_NUMBER_OF_USER_VERIFICATION_ATTEMPTS = 5;

const MAX_NUMBER_OF_USER_VERIFICATION_CODE_TRANSFER_BY_MAIL = 5;

const USER_VERIFICATION_CODE_LENGTH = 6;

const AuthenticationRoutesTag = "Authentication";

export {
	AuthenticationRoutesTag,
	MAX_NUMBER_OF_USER_VERIFICATION_ATTEMPTS,
	MAX_NUMBER_OF_USER_VERIFICATION_CODE_TRANSFER_BY_MAIL,
	USER_VERIFICATION_CODE_LENGTH,
	USER_VERIFICATION_GOALS,
};
